version: 2
jobs:
  build:
    docker:
      - image: tsweetser/diamond:test
    steps:
      - checkout
      - run:
          command: |
            pip3 install -e .
      - run:
          command: |
            nosetests
      - run:
          command: |
            python3 -m "nose"
